src/Entity/Author.php
<?php

namespace App\Entity;

use App\Repository\AuthorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=AuthorRepository::class)
 * @UniqueEntity(fields={"surname", "first_name", "patronymic"})
 */
class Author
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $surname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $patronymic;

    /**
     * @ORM\ManyToMany(targetEntity=Book::class, mappedBy="authors")
     */
    private $books;

    public function __construct()
    {
        $this->books = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getpatronymic(): ?string
    {
        return $this->patronymic;
    }

    public function setpatronymic(?string $patronymic): self
    {
        $this->patronymic = $patronymic;

        return $this;
    }

    public function getFullName(): string
    {
        $fullname[] = $this->surname;
        $fullname[] = $this->first_name;
        if ($this->patronymic) $fullname[] = $this->patronymic;
        return implode(' ', $fullname);
    }

    /**
     * @return Collection<int, Book>
     */
    public function getBooks(): Collection
    {
        return $this->books;
    }

    public function addBook(Book $book): self
    {
        if (!$this->books->contains($book)) {
            $this->books[] = $book;
            $book->addAuthor($this);
        }

        return $this;
    }

    public function removeBook(Book $book): self
    {
        if ($this->books->removeElement($book)) {
            $book->removeAuthor($this);
        }

        return $this;
    }
}

src/Form/AuthorType.php
<?php

namespace App\Form;

use App\Entity\Author;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AuthorType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('surname')
            ->add('first_name')
            ->add('patronymic')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Author::class,
        ]);
    }
}

src/Controller/AuthorController.php
<?php

namespace App\Controller;

use App\Entity\Author;
use App\Form\AuthorType;
use App\Repository\AuthorRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/author")
 */
class AuthorController extends AbstractController
{
    /**
     * @Route("/", name="app_author_index", methods={"GET"})
     */
    public function index(AuthorRepository $authorRepository): Response
    {
        return $this->render('author/index.html.twig', [
            'authors' => $authorRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_author_new", methods={"GET", "POST"})
     */
    public function new(Request $request, AuthorRepository $authorRepository): Response
    {
        $author = new Author();
        $form = $this->createForm(AuthorType::class, $author);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $authorRepository->add($author);
            return $this->redirectToRoute('app_author_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('author/new.html.twig', [
            'author' => $author,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_author_show", methods={"GET"})
     */
    public function show(Author $author): Response
    {
        return $this->render('author/show.html.twig', [
            'author' => $author,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_author_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Author $author, AuthorRepository $authorRepository): Response
    {
        $form = $this->createForm(AuthorType::class, $author);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $authorRepository->add($author);
            return $this->redirectToRoute('app_author_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('author/edit.html.twig', [
            'author' => $author,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_author_delete", methods={"POST"})
     */
    public function delete(Request $request, Author $author, AuthorRepository $authorRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$author->getId(), $request->request->get('_token'))) {
            $authorRepository->remove($author);
        }

        return $this->redirectToRoute('app_author_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/author/_delete_form.html.twig
<form method="post" action="{{ path('app_author_delete', {'id': author.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ author.id) }}">
    <button class="btn">Delete</button>
</form>

templates/author/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/author/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Author{% endblock %}

{% block body %}
    <h1>Edit Author</h1>

    {{ include('author/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_author_index') }}">back to list</a>

    {{ include('author/_delete_form.html.twig') }}
{% endblock %}

templates/author/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Author index{% endblock %}

{% block body %}
    <h1>Author index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Surname</th>
                <th>First_name</th>
                <th>Patronymic</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for author in authors %}
            <tr>
                <td>{{ author.id }}</td>
                <td>{{ author.surname }}</td>
                <td>{{ author.firstName }}</td>
                <td>{{ author.patronymic }}</td>
                <td>
                    <a href="{{ path('app_author_show', {'id': author.id}) }}">show</a>
                    <a href="{{ path('app_author_edit', {'id': author.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_author_new') }}">Create new</a>
{% endblock %}

templates/author/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Author{% endblock %}

{% block body %}
    <h1>Create new Author</h1>

    {{ include('author/_form.html.twig') }}

    <a href="{{ path('app_author_index') }}">back to list</a>
{% endblock %}

templates/author/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Author{% endblock %}

{% block body %}
    <h1>Author</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ author.id }}</td>
            </tr>
            <tr>
                <th>Surname</th>
                <td>{{ author.surname }}</td>
            </tr>
            <tr>
                <th>First_name</th>
                <td>{{ author.firstName }}</td>
            </tr>
            <tr>
                <th>Patronymic</th>
                <td>{{ author.patronymic }}</td>
            </tr>
            <tr>
                <th>Books</th>
                <td>
                    {% for book in author.books %}
                        <a href="{{ path('app_book_show', {'id': book.id}) }}">{{ book.title }}</a><br>
                    {% endfor %}
                </td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_author_index') }}">back to list</a>

    <a href="{{ path('app_author_edit', {'id': author.id}) }}">edit</a>

    {{ include('author/_delete_form.html.twig') }}
{% endblock %}